<?php
/**
 * @desc 国家、货币相关枚举值
 * @author Weixun Luo
 * @date 2014-11-20
 */
class EnumCountry
{
    // 常用国家二位字母代码（ISO 3166标准）
    const AF_CODE = 'AF';
    const AL_CODE = 'AL';
    const DZ_CODE = 'DZ';
    const AS_CODE = 'AS';
    const AD_CODE = 'AD';
    const AO_CODE = 'AO';
    const AI_CODE = 'AI';
    const AG_CODE = 'AG';
    const AA_CODE = 'AA';
    const AR_CODE = 'AR';
    const AM_CODE = 'AM';
    const AW_CODE = 'AW';
    const AU_CODE = 'AU';
    const AT_CODE = 'AT';
    const AZ_CODE = 'AZ';
    const XH_CODE = 'XH';
    const BS_CODE = 'BS';
    const BH_CODE = 'BH';
    const XJ_CODE = 'XJ';
    const BD_CODE = 'BD';
    const BB_CODE = 'BB';
    const BY_CODE = 'BY';
    const BE_CODE = 'BE';
    const BZ_CODE = 'BZ';
    const BJ_CODE = 'BJ';
    const BM_CODE = 'BM';
    const BT_CODE = 'BT';
    const BO_CODE = 'BO';
    const BQ_CODE = 'BQ';  // 跟下面那个重复了，哪个为准？
    const XB_CODE = 'XB';
    const BA_CODE = 'BA';
    const BW_CODE = 'BW';
    const BR_CODE = 'BR';
    const VG_CODE = 'VG';
    const BN_CODE = 'BN';
    const BG_CODE = 'BG';
    const BF_CODE = 'BF';
    const MM_CODE = 'MM';
    const BI_CODE = 'BI';
    const KH_CODE = 'KH';
    const CM_CODE = 'CM';
    const CA_CODE = 'CA';
    const XA_CODE = 'XA';
    const CV_CODE = 'CV';
    const KY_CODE = 'KY';
    const CF_CODE = 'CF';
    const TD_CODE = 'TD';
    const CL_CODE = 'CL';
    const CN_CODE = 'CN';
    const CX_CODE = 'CX';
    const CO_CODE = 'CO';
    const KM_CODE = 'KM';
    const CD_CODE = 'CD';
    const CG_CODE = 'CG';
    const CK_CODE = 'CK';
    const XF_CODE = 'XF';
    const CR_CODE = 'CR';
    const CI_CODE = 'CI';
    const HR_CODE = 'HR';
    const CU_CODE = 'CU';
    const XC_CODE = 'XC';
    const CY_CODE = 'CY';
    const CZ_CODE = 'CZ';
    const DK_CODE = 'DK';
    const DJ_CODE = 'DJ';
    const DM_CODE = 'DM';
    const DO_CODE = 'DO';
    const EC_CODE = 'EC';
    const EG_CODE = 'EG';
    const SV_CODE = 'SV';
    const GQ_CODE = 'GQ';
    const ER_CODE = 'ER';
    const EE_CODE = 'EE';
    const ET_CODE = 'ET';
    const FK_CODE = 'FK';
    const FO_CODE = 'FO';
    const FJ_CODE = 'FJ';
    const FI_CODE = 'FI';
    const FR_CODE = 'FR';
    const GF_CODE = 'GF';
    const PF_CODE = 'PF';
    const GA_CODE = 'GA';
    const GM_CODE = 'GM';
    const GE_CODE = 'GE';
    const DE_CODE = 'DE';
    const GH_CODE = 'GH';
    const GI_CODE = 'GI';
    const GR_CODE = 'GR';
    // const = _CODE'';  // 欢迎补充
    const GL_CODE = 'GL';
    const GD_CODE = 'GD';
    const GP_CODE = 'GP';
    const GU_CODE = 'GU';
    const GT_CODE = 'GT';
    const GG_CODE = 'GG';
    const GN_CODE = 'GN';
    const GW_CODE = 'GW';
    const GY_CODE = 'GY';
    const HT_CODE = 'HT';
    const HM_CODE = 'HM';
    const HN_CODE = 'HN';
    const HK_CODE = 'HK';
    const HU_CODE = 'HU';
    const IS_CODE = 'IS';
    const IN_CODE = 'IN';
    const ID_CODE = 'ID';
    const IR_CODE = 'IR';
    const IQ_CODE = 'IQ';
    const IE_CODE = 'IE';
    const IL_CODE = 'IL';
    const IT_CODE = 'IT';
    const JM_CODE = 'JM';
    const SJ_CODE = 'SJ';
    const JP_CODE = 'JP';
    const JE_CODE = 'JE';
    const JO_CODE = 'JO';
    const KZ_CODE = 'KZ';
    const KE_CODE = 'KE';
    const KI_CODE = 'KI';
    const KP_CODE = 'KP';
    const KR_CODE = 'KR';
    const XO_CODE = 'XO';
    const KW_CODE = 'KW';
    const KG_CODE = 'KG';
    const LA_CODE = 'LA';
    const LV_CODE = 'LV';
    const LB_CODE = 'LB';
    const LS_CODE = 'LS';
    const LR_CODE = 'LR';
    const LY_CODE = 'LY';
    const LI_CODE = 'LI';
    const LT_CODE = 'LT';
    const LU_CODE = 'LU';
    const MO_CODE = 'MO';
    const MK_CODE = 'MK';
    const MG_CODE = 'MG';
    const XI_CODE = 'XI';
    const MW_CODE = 'MW';
    const MY_CODE = 'MY';
    const MV_CODE = 'MV';
    const ML_CODE = 'ML';
    const MT_CODE = 'MT';
    const MH_CODE = 'MH';
    const MQ_CODE = 'MQ';
    const MR_CODE = 'MR';
    const MU_CODE = 'MU';
    const YT_CODE = 'YT';
    const MX_CODE = 'MX';
    const FM_CODE = 'FM';
    const MD_CODE = 'MD';
    const MC_CODE = 'MC';
    const MN_CODE = 'MN';
    const ME_CODE = 'ME';
    const MS_CODE = 'MS';
    const MA_CODE = 'MA';
    const MZ_CODE = 'MZ';
    const NA_CODE = 'NA';
    const NR_CODE = 'NR';
    const NP_CODE = 'NP';
    const NL_CODE = 'NL';
    const AN_CODE = 'AN';
    const NC_CODE = 'NC';
    const NZ_CODE = 'NZ';
    const NI_CODE = 'NI';
    const NE_CODE = 'NE';
    const NG_CODE = 'NG';
    const NU_CODE = 'NU';
    const NF_CODE = 'NF';
    const NO_CODE = 'NO';
    const OM_CODE = 'OM';
    const PK_CODE = 'PK';
    const PW_CODE = 'PW';
    const PA_CODE = 'PA';
    const PG_CODE = 'PG';
    const PY_CODE = 'PY';
    const PE_CODE = 'PE';
    const PH_CODE = 'PH';
    const PN_CODE = 'PN';
    const PL_CODE = 'PL';
    const PT_CODE = 'PT';
    const PR_CODE = 'PR';
    const QA_CODE = 'QA';
    const RE_CODE = 'RE';
    const RO_CODE = 'RO';
    const RU_CODE = 'RU';
    const RW_CODE = 'RW';
    const BL_CODE = 'BL';
    const XN_CODE = 'XN';
    const SH_CODE = 'SH';
    const KN_CODE = 'KN';
    const LC_CODE = 'LC';
    const PM_CODE = 'PM';
    const VC_CODE = 'VC';
    const MP_CODE = 'MP';
    const SM_CODE = 'SM';
    const ST_CODE = 'ST';
    const SA_CODE = 'SA';
    const SN_CODE = 'SN';
    const RS_CODE = 'RS';
    const SC_CODE = 'SC';
    const SL_CODE = 'SL';
    const SG_CODE = 'SG';
    const SK_CODE = 'SK';
    const SI_CODE = 'SI';
    const SB_CODE = 'SB';
    const SO_CODE = 'SO';
    const ZA_CODE = 'ZA';
    const GS_CODE = 'GS';
    const ES_CODE = 'ES';
    const LK_CODE = 'LK';
    const SX_CODE = 'SX';
    const XE_CODE = 'XE';
    const SD_CODE = 'SD';
    const SR_CODE = 'SR';
    const SZ_CODE = 'SZ';
    const SE_CODE = 'SE';
    const CH_CODE = 'CH';
    const SY_CODE = 'SY';
    const TW_CODE = 'TW';
    const TJ_CODE = 'TJ';
    const TZ_CODE = 'TZ';
    const TH_CODE = 'TH';
    const TL_CODE = 'TL';
    const TG_CODE = 'TG';
    const TK_CODE = 'TK';
    const TO_CODE = 'TO';
    const TT_CODE = 'TT';
    const TN_CODE = 'TN';
    const TR_CODE = 'TR';
    const TM_CODE = 'TM';
    const TC_CODE = 'TC';
    const TV_CODE = 'TV';
    const UG_CODE = 'UG';
    const UA_CODE = 'UA';
    const AE_CODE = 'AE';
    const GB_CODE = 'GB';
    const US_CODE = 'US';
    const UY_CODE = 'UY';
    const UZ_CODE = 'UZ';
    const VU_CODE = 'VU';
    const VA_CODE = 'VA';
    const VE_CODE = 'VE';
    const VN_CODE = 'VN';
    const VI_CODE = 'VI';
    const WF_CODE = 'WF';
    const EH_CODE = 'EH';
    const WS_CODE = 'WS';
    const YE_CODE = 'YE';
    const ZM_CODE = 'ZM';
    const ZW_CODE = 'ZW';

    // 国家英文名
    public static $countryNameEn = array(
        self::AF_CODE => 'Afghanistan',
        self::AL_CODE => 'Albania',
        self::DZ_CODE => 'Algeria',
        self::AS_CODE => 'American Samoa',
        self::AD_CODE => 'Andorra',
        self::AO_CODE => 'Angola',
        self::AI_CODE => 'Anguilla',
        self::AG_CODE => 'Antigua and Barbuda',
        self::AA_CODE => 'APO/FPO/DPO',
        self::AR_CODE => 'Argentina',
        self::AM_CODE => 'Armenia',
        self::AW_CODE => 'Aruba',
        self::AU_CODE => 'Australia',
        self::AT_CODE => 'Austria',
        self::AZ_CODE => 'Azerbaijan Republic',
        self::XH_CODE => 'Azores',
        self::BS_CODE => 'Bahamas',
        self::BH_CODE => 'Bahrain',
        self::XJ_CODE => 'Balearic Islands',
        self::BD_CODE => 'Bangladesh',
        self::BB_CODE => 'Barbados',
        self::BY_CODE => 'Belarus',
        self::BE_CODE => 'Belgium',
        self::BZ_CODE => 'Belize',
        self::BJ_CODE => 'Benin',
        self::BM_CODE => 'Bermuda',
        self::BT_CODE => 'Bhutan',
        self::BO_CODE => 'Bolivia',
        self::BQ_CODE => 'Bonaire',  // 跟下面那个重复了，哪个为准？
        self::XB_CODE => 'Bonaire',
        self::BA_CODE => 'Bosnia and Herzegovina',
        self::BW_CODE => 'Botswana',
        self::BR_CODE => 'Brazil',
        self::VG_CODE => 'British Virgin Islands',
        self::BN_CODE => 'Brunei Darussalam',
        self::BG_CODE => 'Bulgaria',
        self::BF_CODE => 'Burkina Faso',
        self::MM_CODE => 'Burma',
        self::BI_CODE => 'Burundi',
        self::KH_CODE => 'Cambodia',
        self::CM_CODE => 'Cameroon',
        self::CA_CODE => 'Canada',
        self::XA_CODE => 'Canary Islands',
        self::CV_CODE => 'Cape Verde Islands',
        self::KY_CODE => 'Cayman Islands',
        self::CF_CODE => 'Central African Republic',
        self::TD_CODE => 'Chad',
        self::CL_CODE => 'Chile',
        self::CN_CODE => 'China',
        self::CX_CODE => 'Christmas Island',
        self::CO_CODE => 'Colombia',
        self::KM_CODE => 'Comoros',
        self::CD_CODE => 'Congo, Democratic Republic of the',
        self::CG_CODE => 'Congo, Republic of the',
        self::CK_CODE => 'Cook Islands',
        self::XF_CODE => 'Corsica',
        self::CR_CODE => 'Costa Rica',
        self::CI_CODE => 'Cote d Ivoire (Ivory Coast)',
        self::HR_CODE => 'Croatia, Republic of',
        self::CU_CODE => 'Cuba',
        self::XC_CODE => 'Curacao',
        self::CY_CODE => 'Cyprus',
        self::CZ_CODE => 'Czech Republic',
        self::DK_CODE => 'Denmark',
        self::DJ_CODE => 'Djibouti',
        self::DM_CODE => 'Dominica',
        self::DO_CODE => 'Dominican Republic',
        self::EC_CODE => 'Ecuador',
        self::EG_CODE => 'Egypt',
        self::SV_CODE => 'El Salvador',
        self::GQ_CODE => 'Equatorial Guinea',
        self::ER_CODE => 'Eritrea',
        self::EE_CODE => 'Estonia',
        self::ET_CODE => 'Ethiopia',
        self::FK_CODE => 'Falkland Islands (Islas Malvinas)',
        self::FO_CODE => 'Faroe Islands',
        self::FJ_CODE => 'Fiji',
        self::FI_CODE => 'Finland',
        self::FR_CODE => 'France',
        self::GF_CODE => 'French Guiana',
        self::PF_CODE => 'French Polynesia(Tahiti)',
        self::GA_CODE => 'Gabon Republic',
        self::GM_CODE => 'Gambia',
        self::GE_CODE => 'Georgia',
        self::DE_CODE => 'Germany',
        self::GH_CODE => 'Ghana',
        self::GI_CODE => 'Gibraltar',
        self::GR_CODE => 'Greece',
        // self::_CODE => 'Greek Islands',  // 欢迎补充
        self::GL_CODE => 'Greenland',
        self::GD_CODE => 'Grenada',
        self::GP_CODE => 'Guadeloupe',
        self::GU_CODE => 'Guam',
        self::GT_CODE => 'Guatemala',
        self::GG_CODE => 'Channel Islands-Guernsey',
        self::GN_CODE => 'Guinea',
        self::GW_CODE => 'Guinea-Bissau',
        self::GY_CODE => 'Guyana',
        self::HT_CODE => 'Haiti',
        self::HM_CODE => 'Heard Island and McDonald Islands',
        self::HN_CODE => 'Honduras',
        self::HK_CODE => 'Hong Kong',
        self::HU_CODE => 'Hungary',
        self::IS_CODE => 'Iceland',
        self::IN_CODE => 'India',
        self::ID_CODE => 'Indonesia',
        self::IR_CODE => 'Iran',
        self::IQ_CODE => 'Iraq',
        self::IE_CODE => 'Ireland(Irish Republic)',
        self::IL_CODE => 'Israel',
        self::IT_CODE => 'Italy',
        self::JM_CODE => 'Jamaica',
        self::SJ_CODE => 'Jan Mayen(Svalbard)',
        self::JP_CODE => 'Japan',
        self::JE_CODE => 'Jersey',
        self::JO_CODE => 'Jordan',
        self::KZ_CODE => 'Kazakhstan',
        self::KE_CODE => 'Kenya',
        self::KI_CODE => 'Kiribati',
        self::KP_CODE => 'Korea, North',
        self::KR_CODE => 'Korea, South',
        self::XO_CODE => 'Kosovo',
        self::KW_CODE => 'Kuwait',
        self::KG_CODE => 'Kyrgyzstan',
        self::LA_CODE => 'Laos',
        self::LV_CODE => 'Latvia',
        self::LB_CODE => 'Lebanon',
        self::LS_CODE => 'Lesotho',
        self::LR_CODE => 'Liberia',
        self::LY_CODE => 'Libya',
        self::LI_CODE => 'Liechtenstein',
        self::LT_CODE => 'Lithuania',
        self::LU_CODE => 'Luxembourg',
        self::MO_CODE => 'Macau',
        self::MK_CODE => 'Macedonia',
        self::MG_CODE => 'Madagascar',
        self::XI_CODE => 'Madeira',
        self::MW_CODE => 'Malawi',
        self::MY_CODE => 'Malaysia',
        self::MV_CODE => 'Maldives',
        self::ML_CODE => 'Mali',
        self::MT_CODE => 'Malta',
        self::MH_CODE => 'Marshall Islands',
        self::MQ_CODE => 'Martinique',
        self::MR_CODE => 'Mauritania',
        self::MU_CODE => 'Mauritius',
        self::YT_CODE => 'Mayotte',
        self::MX_CODE => 'Mexico',
        self::FM_CODE => 'Micronesia',
        self::MD_CODE => 'Moldova',
        self::MC_CODE => 'Monaco',
        self::MN_CODE => 'Mongolia',
        self::ME_CODE => 'Montenegro',
        self::MS_CODE => 'Montserrat',
        self::MA_CODE => 'Morocco',
        self::MZ_CODE => 'Mozambique',
        self::NA_CODE => 'Namibia',
        self::NR_CODE => 'Nauru',
        self::NP_CODE => 'Nepal',
        self::NL_CODE => 'Netherlands',
        self::AN_CODE => 'Netherlands Antilles',
        self::NC_CODE => 'New Caledonia',
        self::NZ_CODE => 'New Zealand',
        self::NI_CODE => 'Nicaragua',
        self::NE_CODE => 'Niger',
        self::NG_CODE => 'Nigeria',
        self::NU_CODE => 'Niue',
        self::NF_CODE => 'Norfolk Island',
        self::NO_CODE => 'Norway',
        self::OM_CODE => 'Oman',
        self::PK_CODE => 'Pakistan',
        self::PW_CODE => 'Palau',
        self::PA_CODE => 'Panama',
        self::PG_CODE => 'Papua New Guinea',
        self::PY_CODE => 'Paraguay',
        self::PE_CODE => 'Peru',
        self::PH_CODE => 'Philippines',
        self::PN_CODE => 'Pitcairn',
        self::PL_CODE => 'Poland',
        self::PT_CODE => 'Portugal',
        self::PR_CODE => 'Puerto Rico',
        self::QA_CODE => 'Qatar',
        self::RE_CODE => 'Reunion Island Of',
        self::RO_CODE => 'Romania',
        self::RU_CODE => 'Russian Federation',
        self::RW_CODE => 'Rwanda',
        self::BL_CODE => 'Saint BarthASlemy(St Barthelemy)',
        self::XN_CODE => 'Saint Christopher and Nevis',
        self::SH_CODE => 'Saint Helena',
        self::KN_CODE => 'Saint Kitts-Nevis',
        self::LC_CODE => 'Saint Lucia',
        self::PM_CODE => 'Saint Pierre and Miquelon',
        self::VC_CODE => 'Saint Vincent and the Grenadines',
        self::MP_CODE => 'Saipan',
        self::SM_CODE => 'San Marino',
        self::ST_CODE => 'Sao Tome and Principe',
        self::SA_CODE => 'Saudi Arabia',
        self::SN_CODE => 'Senegal',
        self::RS_CODE => 'Serbia',
        self::SC_CODE => 'Seychelles',
        self::SL_CODE => 'Sierra Leone',
        self::SG_CODE => 'Singapore',
        self::SK_CODE => 'Slovakia',
        self::SI_CODE => 'Slovenia',
        self::SB_CODE => 'Solomon Islands',
        self::SO_CODE => 'Somalia',
        self::ZA_CODE => 'South Africa',
        self::GS_CODE => 'South Georgia and the South Sandwich Islands',
        self::ES_CODE => 'Spain',
        self::LK_CODE => 'Sri Lanka',
        self::SX_CODE => 'St.Maarten',
        self::XE_CODE => 'St.Eustatius',
        self::SD_CODE => 'Sudan',
        self::SR_CODE => 'Suriname',
        self::SZ_CODE => 'Swaziland',
        self::SE_CODE => 'Sweden',
        self::CH_CODE => 'Switzerland',
        self::SY_CODE => 'Syria',
        self::TW_CODE => 'Taiwan',
        self::TJ_CODE => 'Tajikistan',
        self::TZ_CODE => 'Tanzania',
        self::TH_CODE => 'Thailand',
        self::TL_CODE => 'Timor-Leste(East Timor)',
        self::TG_CODE => 'Togo',
        self::TK_CODE => 'Tokelau',
        self::TO_CODE => 'Tonga',
        self::TT_CODE => 'Trinidad and Tobago',
        self::TN_CODE => 'Tunisia',
        self::TR_CODE => 'Turkey',
        self::TM_CODE => 'Turkmenistan',
        self::TC_CODE => 'Turks and Caicos Islands',
        self::TV_CODE => 'Tuvalu',
        self::UG_CODE => 'Uganda',
        self::UA_CODE => 'Ukraine',
        self::AE_CODE => 'United Arab Emirates',
        self::GB_CODE => 'United Kingdom',
        self::US_CODE => 'United States',
        self::UY_CODE => 'Uruguay',
        self::UZ_CODE => 'Uzbekistan',
        self::VU_CODE => 'Vanuatu',
        self::VA_CODE => 'Vatican City State',
        self::VE_CODE => 'Venezuela',
        self::VN_CODE => 'Vietnam',
        self::VI_CODE => 'Virgin Islands (U.S.)',
        self::WF_CODE => 'Wallis and Futuna',
        self::EH_CODE => 'Western Sahara',
        self::WS_CODE => 'Western Samoa',
        self::YE_CODE => 'Yemen',
        self::ZM_CODE => 'Zambia',
        self::ZW_CODE => 'Zimbabwe'
    );
}